export type IELTSPart = 1 | 2 | 3;

export type Part1Topic = {
  id: string;
  topic: string;
  category: string;
  questions: string[];
};

export type Part2CueCard = {
  id: string;
  topic: string;
  category: "person" | "place" | "object" | "event" | "activity";
  prompt: string;
  points: string[];
  explain: string;
  part3CategoryId: string;
};

export type Part3Category = {
  id: string;
  topic: string;
  questions: string[];
};

export type IELTSQuestionBank = {
  part1: Part1Topic[];
  part2: Part2CueCard[];
  part3: Part3Category[];
};

export const ieltsQuestionBank: IELTSQuestionBank = {
  part1: [
    {
      id: "p1-work",
      topic: "Work",
      category: "Mandatory",
      questions: [
        "What is your job?",
        "Where do you work?",
        "Why did you choose that job?",
        "Is it a popular job in your country?",
        "Do you like your job?",
      ],
    },
    {
      id: "p1-study",
      topic: "Study",
      category: "Mandatory",
      questions: [
        "What do you study?",
        "Where do you study that?",
        "Why did you choose that subject?",
        "Is it a popular subject in your country?",
        "What was your first day like?",
      ],
    },
    {
      id: "p1-hometown",
      topic: "Hometown",
      category: "Mandatory",
      questions: [
        "Where is your hometown?",
        "Do you like your hometown?",
        "What is your hometown like?",
        "How could your hometown be improved?",
        "Has your hometown changed much since you were a child?",
      ],
    },
    {
      id: "p1-home",
      topic: "Home/Accommodation",
      category: "Mandatory",
      questions: [
        "Where is your home?",
        "Do you live in a house or a flat?",
        "Who do you live with?",
        "What is your favourite room?",
        "What would you change about your home?",
      ],
    },
    {
      id: "p1-hobbies",
      topic: "Hobbies",
      category: "Personal",
      questions: [
        "Do you have a hobby?",
        "What equipment do you need for it?",
        "Did you have a hobby as a child?",
        "What hobbies are popular in your country?",
      ],
    },
    {
      id: "p1-food",
      topic: "Food",
      category: "Daily Life",
      questions: [
        "What is your favourite food?",
        "Have you always liked the same food?",
        "Is there any food you dislike?",
        "What is a common meal in your country?",
        "Do you have a healthy diet?",
      ],
    },
    {
      id: "p1-music",
      topic: "Music",
      category: "Arts & Entertainment",
      questions: [
        "Do you like music?",
        "What is your favourite type of music?",
        "Can you sing?",
        "Did you learn music at school?",
        "If you could learn a musical instrument, what would it be?",
      ],
    },
    {
      id: "p1-reading",
      topic: "Reading",
      category: "Arts & Entertainment",
      questions: [
        "Do you often read?",
        "What is your favourite kind of book to read?",
        "Do you have any e-books?",
        "What books did you read as a child?",
      ],
    },
    {
      id: "p1-sport",
      topic: "Sport",
      category: "Health & Activity",
      questions: [
        "Do you like sport?",
        "What is your favourite sport?",
        "Do you often watch sport on TV?",
        "What is the most popular sport in your country?",
      ],
    },
    {
      id: "p1-travel",
      topic: "Travel",
      category: "Personal",
      questions: [
        "Do you like travelling?",
        "Where did you go on your last holiday?",
        "Do you prefer travelling alone or with others?",
        "Where would you like to travel in the future?",
      ],
    },
    {
      id: "p1-weather",
      topic: "Weather",
      category: "Daily Life",
      questions: [
        "What is the weather like today?",
        "What is your favourite weather?",
        "Do you like the weather in your country?",
        "Does the weather ever affect the way you feel?",
      ],
    },
    {
      id: "p1-internet",
      topic: "Internet",
      category: "Technology",
      questions: [
        "How often do you go online?",
        "What do you use the internet for?",
        "What is your favourite website?",
        "Do you think children should be allowed unsupervised access to the internet?",
      ],
    },
    {
      id: "p1-friends",
      topic: "Family & Friends",
      category: "Personal",
      questions: [
        "Do you spend much time with your family?",
        "Who are you closest to in your family?",
        "Do you prefer spending time with your family or friends?",
        "Is family important in your country?",
      ],
    },
    {
      id: "p1-daily-routine",
      topic: "Daily Routine",
      category: "Daily Life",
      questions: [
        "When do you usually get up in the morning?",
        "Do you usually have the same routine every day?",
        "What is your daily routine?",
        "Do you think it is important to have a daily routine?",
      ],
    },
    {
      id: "p1-clothes",
      topic: "Clothes",
      category: "Personal",
      questions: [
        "Are clothes important to you?",
        "What kind of clothes do you usually wear?",
        "Do you ever wear the traditional clothes of your country?",
        "Where do you usually buy your clothes?",
      ],
    },
    {
      id: "p1-tv",
      topic: "TV",
      category: "Arts & Entertainment",
      questions: [
        "Do you often watch TV?",
        "What sorts of things do you watch on TV?",
        "What is your favourite TV program?",
        "What did you watch on TV when you were a child?",
      ],
    },
    {
      id: "p1-transport",
      topic: "Transport",
      category: "Daily Life",
      questions: [
        "How did you get here today?",
        "What is your favourite mode of transport?",
        "Do you ever use public transport?",
        "What is the difference between taking a bus and taking a train?",
      ],
    },
    {
      id: "p1-shopping",
      topic: "Shopping",
      category: "Daily Life",
      questions: [
        "Do you like shopping?",
        "What is your favourite shop?",
        "Do you prefer shopping alone or with others?",
        "Have you ever bought anything online?",
      ],
    },
    {
      id: "p1-languages",
      topic: "Languages",
      category: "Education",
      questions: [
        "How many foreign languages do you speak?",
        "When did you start learning your first foreign language?",
        "How many foreign languages do children in your country learn at school?",
        "Do you think it is important to learn a foreign language?",
      ],
    },
    {
      id: "p1-childhood",
      topic: "Childhood",
      category: "Personal",
      questions: [
        "Did you enjoy your childhood?",
        "What is your first memory of your childhood?",
        "Did you have a lot of friends when you were a child?",
        "What did you enjoy doing as a child?",
      ],
    },
  ],
  part2: [
    {
      id: "p2-family-member",
      topic: "A family member you get on well with",
      category: "person",
      prompt: "Describe a member of your family you get on well with.",
      points: [
        "who it is",
        "what relationship you have to that person",
        "what that person is like",
        "what you do together",
      ],
      explain: "and explain why you get on so well.",
      part3CategoryId: "p3-family",
    },
    {
      id: "p2-best-friend",
      topic: "Your best friend",
      category: "person",
      prompt: "Describe your best friend.",
      points: [
        "who this person is",
        "what they are like",
        "how you first met",
        "what you do together",
      ],
      explain: "and explain why this person is your best friend.",
      part3CategoryId: "p3-friendship",
    },
    {
      id: "p2-respect-person",
      topic: "Someone you respect",
      category: "person",
      prompt: "Describe someone you respect.",
      points: [
        "who the person is",
        "how you know about this person",
        "what this person does",
        "what this person is like",
      ],
      explain: "and explain why you respect this person.",
      part3CategoryId: "p3-success",
    },
    {
      id: "p2-teacher",
      topic: "A teacher you admired",
      category: "person",
      prompt: "Describe a teacher you admired.",
      points: [
        "who it was",
        "what they taught",
        "what you enjoyed about their lessons",
        "how they taught",
      ],
      explain: "and explain why you admired them.",
      part3CategoryId: "p3-education",
    },
    {
      id: "p2-old-person",
      topic: "An old person you know",
      category: "person",
      prompt: "Describe an old person you know.",
      points: [
        "who this person is",
        "how old he/she is",
        "what this person is like",
        "what you do together",
      ],
      explain: "and explain why you like this person.",
      part3CategoryId: "p3-family",
    },
    {
      id: "p2-successful-person",
      topic: "A successful person",
      category: "person",
      prompt: "Describe someone who is successful.",
      points: [
        "who it is",
        "what they are like",
        "what they do",
        "how they achieved success",
      ],
      explain: "and explain why you think they are successful.",
      part3CategoryId: "p3-success",
    },
    {
      id: "p2-recent-visit",
      topic: "A place you recently visited",
      category: "place",
      prompt: "Describe a place you have recently visited.",
      points: [
        "where you went",
        "who you went with",
        "how you got there",
        "what you did there",
      ],
      explain: "and explain why you enjoyed it.",
      part3CategoryId: "p3-travel",
    },
    {
      id: "p2-peaceful-place",
      topic: "A peaceful place",
      category: "place",
      prompt: "Describe a place that you find peaceful.",
      points: [
        "where it is",
        "when you first went there",
        "what you do there",
        "who you go with",
      ],
      explain: "and explain why you find it peaceful.",
      part3CategoryId: "p3-environment",
    },
    {
      id: "p2-near-water",
      topic: "A place near water",
      category: "place",
      prompt: "Describe a place near water.",
      points: [
        "where it is",
        "how you get there",
        "how often you go there",
        "what you can do there",
      ],
      explain: "and explain why you like it.",
      part3CategoryId: "p3-environment",
    },
    {
      id: "p2-ideal-house",
      topic: "Your ideal house",
      category: "place",
      prompt: "Describe your ideal house.",
      points: [
        "what it would look like",
        "where it would be",
        "what facilities it would have",
        "how it would be decorated",
      ],
      explain: "and explain why you would find it ideal.",
      part3CategoryId: "p3-buildings",
    },
    {
      id: "p2-city-visit",
      topic: "A city you would like to visit",
      category: "place",
      prompt: "Describe a city you would like to visit.",
      points: [
        "where it is",
        "what it is like",
        "what you would want to do there",
        "how you would get there",
      ],
      explain: "and explain why you would enjoy visiting it.",
      part3CategoryId: "p3-travel",
    },
    {
      id: "p2-historical-building",
      topic: "A historical building",
      category: "place",
      prompt: "Describe a historical building in your country.",
      points: [
        "where it is",
        "what it is like",
        "what it is used for",
        "when it was built",
      ],
      explain: "and explain why you think it is important.",
      part3CategoryId: "p3-buildings",
    },
    {
      id: "p2-book",
      topic: "A book you recently read",
      category: "object",
      prompt: "Describe a book you have recently read.",
      points: [
        "what kind of book it is",
        "what it is about",
        "what sort of people would enjoy it",
        "when you read it",
      ],
      explain: "and explain why you liked it.",
      part3CategoryId: "p3-books",
    },
    {
      id: "p2-gift",
      topic: "A gift you recently gave",
      category: "object",
      prompt: "Describe a gift you recently gave to someone.",
      points: [
        "who you gave it to",
        "what kind of person he/she is",
        "what the gift was",
        "what occasion the gift was for",
      ],
      explain: "and explain why you chose that gift.",
      part3CategoryId: "p3-socialising",
    },
    {
      id: "p2-photograph",
      topic: "A photograph you like",
      category: "object",
      prompt: "Describe a photograph you like.",
      points: [
        "what can be seen in the photo",
        "when it was taken",
        "who took it",
        "where it is kept",
      ],
      explain: "and explain why you like it.",
      part3CategoryId: "p3-photography",
    },
    {
      id: "p2-song",
      topic: "A song you like",
      category: "object",
      prompt: "Describe a song you like.",
      points: [
        "what kind of song it is",
        "what the song is about",
        "when you first heard it",
        "how often you listen to it",
      ],
      explain: "and explain why you like it.",
      part3CategoryId: "p3-media",
    },
    {
      id: "p2-useful-app",
      topic: "A useful app",
      category: "object",
      prompt: "Describe a useful app.",
      points: [
        "what it is",
        "how you heard about it",
        "what it does",
        "how often you use it",
      ],
      explain: "and explain why you find it useful.",
      part3CategoryId: "p3-technology",
    },
    {
      id: "p2-art",
      topic: "A piece of art you like",
      category: "object",
      prompt: "Describe a piece of art you like.",
      points: [
        "what the work of art is",
        "when you first saw it",
        "what you know about it",
        "where it is",
      ],
      explain: "and explain why you like it.",
      part3CategoryId: "p3-art",
    },
    {
      id: "p2-good-news",
      topic: "Good news you received",
      category: "event",
      prompt: "Describe some good news you recently received.",
      points: [
        "what the news was",
        "how you received the news",
        "who gave it to you",
        "when you received it",
      ],
      explain: "and explain why this was good news.",
      part3CategoryId: "p3-media",
    },
    {
      id: "p2-journey-unplanned",
      topic: "A journey that didn't go as planned",
      category: "event",
      prompt: "Describe a journey that didn't go as planned.",
      points: [
        "where you were going",
        "how you were travelling",
        "who you were with",
        "what went wrong",
      ],
      explain: "and explain what you would do differently.",
      part3CategoryId: "p3-travel",
    },
    {
      id: "p2-happy-event",
      topic: "A happy event",
      category: "event",
      prompt: "Describe a happy event you remember.",
      points: [
        "when it was",
        "who was with you",
        "what you did",
        "where it happened",
      ],
      explain: "and explain why it was a happy event.",
      part3CategoryId: "p3-socialising",
    },
    {
      id: "p2-mistake",
      topic: "A time you made a mistake",
      category: "event",
      prompt: "Describe a time you made a mistake.",
      points: [
        "when it was",
        "who was there",
        "what happened",
        "how you felt",
      ],
      explain: "and explain what you learned from it.",
      part3CategoryId: "p3-decision",
    },
    {
      id: "p2-embarrassing",
      topic: "A time you were embarrassed",
      category: "event",
      prompt: "Describe a time you were embarrassed.",
      points: [
        "when it was",
        "who you were with",
        "what happened",
        "how you coped afterwards",
      ],
      explain: "and explain why it was embarrassing.",
      part3CategoryId: "p3-socialising",
    },
    {
      id: "p2-challenge",
      topic: "A tough challenge you faced",
      category: "event",
      prompt: "Describe a tough challenge you have faced.",
      points: [
        "what it was",
        "when it happened",
        "how you coped with it",
        "who helped you",
      ],
      explain: "and explain why you remember it.",
      part3CategoryId: "p3-challenges",
    },
    {
      id: "p2-hobby",
      topic: "An interesting hobby",
      category: "activity",
      prompt: "Describe an interesting hobby.",
      points: [
        "what it is",
        "what kind of people do it",
        "how it is done",
        "what equipment is needed",
      ],
      explain: "and explain why you think it is interesting.",
      part3CategoryId: "p3-socialising",
    },
    {
      id: "p2-relax",
      topic: "Something you do to relax",
      category: "activity",
      prompt: "Describe something you do to relax.",
      points: [
        "what it is",
        "where you do it",
        "when you first did it",
        "how often you do it",
      ],
      explain: "and explain why you find it relaxing.",
      part3CategoryId: "p3-health",
    },
    {
      id: "p2-sport-learn",
      topic: "A sport you would like to learn",
      category: "activity",
      prompt: "Describe a sport you would like to learn.",
      points: [
        "what it is",
        "what equipment is needed for it",
        "how you would learn it",
        "where you could do it",
      ],
      explain: "and explain why you would like to learn this sport.",
      part3CategoryId: "p3-health",
    },
    {
      id: "p2-exercise",
      topic: "An exercise you know",
      category: "activity",
      prompt: "Describe an exercise you know.",
      points: [
        "what it is",
        "how it is done",
        "when you first tried it",
        "what kind of people it is suitable for",
      ],
      explain: "and explain why you think it is a good exercise.",
      part3CategoryId: "p3-health",
    },
    {
      id: "p2-outdoor-activity",
      topic: "An outdoor activity you enjoy",
      category: "activity",
      prompt: "Describe an outdoor activity you enjoy.",
      points: [
        "what it is",
        "where you do it",
        "how you do it",
        "who you do it with",
      ],
      explain: "and explain why you enjoy it.",
      part3CategoryId: "p3-environment",
    },
    {
      id: "p2-healthy-activity",
      topic: "A healthy activity",
      category: "activity",
      prompt: "Describe a healthy activity.",
      points: [
        "what it is",
        "how it is done",
        "who can enjoy it",
        "how often you do it",
      ],
      explain: "and explain why you think it is healthy.",
      part3CategoryId: "p3-health",
    },
  ],
  part3: [
    {
      id: "p3-family",
      topic: "Family",
      questions: [
        "Is family important in your country?",
        "How has the size of the family changed in the last few decades?",
        "How do you think the family will change in the future?",
        "What role do grandparents play in the family in your country?",
        "Who do you think should be responsible for the care of the elderly?",
      ],
    },
    {
      id: "p3-friendship",
      topic: "Friendship",
      questions: [
        "How do people in your country meet new people?",
        "Do you think it is important for friends to spend time together?",
        "What kinds of things do friends in your country like to do together?",
        "Do you think families spend enough time together these days?",
        "How has socialising changed over the last few decades?",
      ],
    },
    {
      id: "p3-success",
      topic: "Success",
      questions: [
        "Why do you think some people are more successful than others?",
        "Do you think success is innate?",
        "What skills are important to achieve well in life?",
        "Why are some people successful only later in life?",
        "What makes a company successful?",
      ],
    },
    {
      id: "p3-education",
      topic: "Education",
      questions: [
        "What makes a good student?",
        "Do you think computers will one day replace teachers in the classroom?",
        "How has teaching changed in your country in the last few decades?",
        "What is the difference between the way children learn and the way adults learn?",
        "What are the advantages and disadvantages of online learning?",
      ],
    },
    {
      id: "p3-travel",
      topic: "Travel & Holidays",
      questions: [
        "Do men and women enjoy the same kinds of holidays?",
        "How do you think holidays will change in the future?",
        "What kind of holidays do older people enjoy?",
        "What are the pros and cons of tourism for a country?",
        "Do you think tourism is good for historical places?",
      ],
    },
    {
      id: "p3-environment",
      topic: "Environment & Nature",
      questions: [
        "What are the biggest environmental problems in your country?",
        "What should individuals be doing to protect the natural environment?",
        "How could the government help prevent pollution?",
        "Do you think young people today are more aware of environmental problems?",
        "Do you think cities should build more green spaces?",
      ],
    },
    {
      id: "p3-buildings",
      topic: "Buildings & Architecture",
      questions: [
        "Do you think it is important to conserve all old buildings?",
        "Why do people enjoy visiting historical buildings?",
        "Why are people so interested in tall buildings?",
        "How do you think buildings will change in the future?",
        "What are the differences between houses in rural areas and those in cities?",
      ],
    },
    {
      id: "p3-books",
      topic: "Books & Reading",
      questions: [
        "Do you think paper books will ever disappear?",
        "What do children gain from reading books?",
        "How can children be encouraged to read more?",
        "Why do some adults read children's books?",
        "What makes a novel successful?",
      ],
    },
    {
      id: "p3-media",
      topic: "Media & News",
      questions: [
        "How do most people get their news in your country?",
        "Do you believe everything you read in the newspapers?",
        "How do you think people will get their news in the future?",
        "How has TV changed our lives?",
        "Should children be allowed to watch a lot of TV?",
      ],
    },
    {
      id: "p3-technology",
      topic: "Technology & Internet",
      questions: [
        "Do most people have a computer at home in your country?",
        "Do you think all information on the internet is true?",
        "How has the internet changed the way we live?",
        "How has the internet changed the way we work?",
        "Do you think the internet is safe for children to use unsupervised?",
      ],
    },
    {
      id: "p3-health",
      topic: "Health",
      questions: [
        "How can people improve their health?",
        "Do elderly people do much exercise in your country?",
        "Do you think all illness can be prevented?",
        "Do you think health care should be free?",
        "Do you think modern technology is making people less healthy?",
      ],
    },
    {
      id: "p3-art",
      topic: "Art & Creativity",
      questions: [
        "What role does art play in society?",
        "Do you think photos will one day replace paintings?",
        "Do you think people today are less creative than in the past due to advanced technology?",
        "Should the government support the arts?",
        "How can children benefit from art?",
      ],
    },
    {
      id: "p3-photography",
      topic: "Photography",
      questions: [
        "Do many people like taking photos in your country?",
        "What types of photos do people like to take?",
        "What do you think of selfies?",
        "Do you think it is ok to share photos online without people's permission?",
        "How does a photo differ from a painting?",
      ],
    },
    {
      id: "p3-socialising",
      topic: "Socialising",
      questions: [
        "How do people in your country meet new people?",
        "Do you think it is safe to meet new people online?",
        "Do you think it is important for friends to spend time together?",
        "What kinds of things do friends in your country like to do together?",
        "How has socialising changed over the last few decades?",
      ],
    },
    {
      id: "p3-challenges",
      topic: "Challenges",
      questions: [
        "Why do some people relish a challenge?",
        "Are challenges good for us?",
        "Why do some people avoid challenges?",
        "Do you think some people are born more adventurous than others?",
        "What are the greatest challenges people face in the world today?",
      ],
    },
    {
      id: "p3-decision",
      topic: "Decision Making",
      questions: [
        "Why do some people find it difficult to make decisions?",
        "What kinds of big decisions do people have to make in their lives?",
        "Do you think people ought to get advice before making big decisions?",
        "Should children be allowed to make decisions on their own?",
        "Do you think it is better to make decisions quickly or slowly?",
      ],
    },
    {
      id: "p3-work",
      topic: "Work & Career",
      questions: [
        "Do you think job satisfaction is more important than salary when choosing a job?",
        "What skills do you think are needed to get a good job these days?",
        "How has technology changed the way we work?",
        "What jobs do you think are most valuable to society?",
        "At what age should people be allowed to retire?",
      ],
    },
  ],
};
